"""signal snapshot cache for the public signal api

Revision ID: d7bfc163ccc1
Revises: c6cd257fc22f
Create Date: 2026-09-29 03:24:29.169024+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = 'd7bfc163ccc1'
down_revision: Union[str, None] = 'c6cd257fc22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signalsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'captured_on', name='uq_signal_snapshot_ticker_day')
    )
    with op.batch_alter_table('signalsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signalsnapshot_captured_on'), ['captured_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_signalsnapshot_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signalsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signalsnapshot_ticker'))
        batch_op.drop_index(batch_op.f('ix_signalsnapshot_captured_on'))

    op.drop_table('signalsnapshot')
    # ### end Alembic commands ###
