"""baseline schema

Revision ID: c526269fa3c8
Revises:
Create Date: 2026-07-22 19:24:34.134683+00:00

The schema as it existed when versioned migrations were introduced —
autogenerated from the SQLModel metadata rather than hand-transcribed, so it
matches the models exactly.

IMPORTANT for already-deployed databases: this revision CREATEs all seven
tables, so running it against a database that predates Alembic would fail with
"table already exists". Those databases are *stamped* at this revision instead
of upgraded through it — see db.run_migrations(), which distinguishes an empty
database (upgrade, creating everything) from a populated pre-Alembic one
(stamp, recording that it is already at this revision without re-running the
DDL). The `is_admin`/`is_banned`/`nickname`/`alerts_seen_at` columns that the
retired db.ensure_columns() used to bolt on at boot are part of this baseline,
so a stamped database already has them.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = 'c526269fa3c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pageview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pageview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pageview_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pageview_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_pageview_user_email'), ['user_email'], unique=False)

    op.create_table('scoresnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_on', sa.Date(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'captured_on', name='uq_snapshot_ticker_day')
    )
    with op.batch_alter_table('scoresnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoresnapshot_captured_on'), ['captured_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoresnapshot_ticker'), ['ticker'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alerts_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('analystpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analystpost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analystpost_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analystpost_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_analystpost_user_id'), ['user_id'], unique=False)

    op.create_table('watchlistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_watchlist_user_ticker')
    )
    with op.batch_alter_table('watchlistitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlistitem_user_id'), ['user_id'], unique=False)

    op.create_table('postreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['analystpost.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'post_id', name='uq_postreport_user_post')
    )
    with op.batch_alter_table('postreport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postreport_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_postreport_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postreport_reporter_id'), ['reporter_id'], unique=False)

    op.create_table('postvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['analystpost.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_postvote_user_post')
    )
    with op.batch_alter_table('postvote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postvote_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postvote_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postvote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postvote_user_id'))
        batch_op.drop_index(batch_op.f('ix_postvote_post_id'))

    op.drop_table('postvote')
    with op.batch_alter_table('postreport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postreport_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_postreport_post_id'))
        batch_op.drop_index(batch_op.f('ix_postreport_created_at'))

    op.drop_table('postreport')
    with op.batch_alter_table('watchlistitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlistitem_user_id'))

    op.drop_table('watchlistitem')
    with op.batch_alter_table('analystpost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analystpost_user_id'))
        batch_op.drop_index(batch_op.f('ix_analystpost_ticker'))
        batch_op.drop_index(batch_op.f('ix_analystpost_created_at'))

    op.drop_table('analystpost')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('scoresnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoresnapshot_ticker'))
        batch_op.drop_index(batch_op.f('ix_scoresnapshot_captured_on'))

    op.drop_table('scoresnapshot')
    with op.batch_alter_table('pageview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pageview_user_email'))
        batch_op.drop_index(batch_op.f('ix_pageview_path'))
        batch_op.drop_index(batch_op.f('ix_pageview_created_at'))

    op.drop_table('pageview')
    # ### end Alembic commands ###
