"""email alert settings on watchlist and user

Revision ID: c6cd257fc22f
Revises: 33932668e0c4
Create Date: 2026-08-11 04:38:46.190237+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = 'c6cd257fc22f'
down_revision: Union[str, None] = '33932668e0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Hand-corrected after autogenerate, per CLAUDE.md §3.4 ("READ the
    # generated file"): alembic emitted `email_alerts_enabled` as
    # `nullable=False` with NO server_default. Adding a NOT NULL column with no
    # default to a table that already has rows has nothing to put in those
    # rows — on SQLite's batch rebuild every existing account would get NULL in
    # a NOT NULL column, and on PostgreSQL the ALTER simply fails. The model
    # default (`email_alerts_enabled: bool = True`) is a Python-side default
    # applied on INSERT; it does not backfill anything.
    #
    # server_default backfills existing accounts to opted-IN, which matches the
    # model default and the product rule: a user who configures a per-stock
    # alert has asked to be emailed. sa.true() renders as `1` on SQLite and
    # `true` on PostgreSQL, so this migration is portable across both.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'email_alerts_enabled',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    with op.batch_alter_table('watchlistitem', schema=None) as batch_op:
        # All three nullable on purpose — NULL is "this trigger is off", and a
        # row that predates alerts is correctly off rather than opted in.
        batch_op.add_column(sa.Column('alert_threshold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alert_spike_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('alert_sent_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlistitem', schema=None) as batch_op:
        batch_op.drop_column('alert_sent_at')
        batch_op.drop_column('alert_spike_points')
        batch_op.drop_column('alert_threshold')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_alerts_enabled')

    # ### end Alembic commands ###
