"""audit log

Revision ID: 33932668e0c4
Revises: c526269fa3c8
Create Date: 2026-07-22 20:57:41.886262+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = '33932668e0c4'
down_revision: Union[str, None] = 'c526269fa3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlog_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditlog_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditlog_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditlog_target'), ['target'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlog_target'))
        batch_op.drop_index(batch_op.f('ix_auditlog_created_at'))
        batch_op.drop_index(batch_op.f('ix_auditlog_actor_email'))
        batch_op.drop_index(batch_op.f('ix_auditlog_action'))

    op.drop_table('auditlog')
    # ### end Alembic commands ###
