"""Regenerate the replay viewer's bundled sample journeys.

    .venv/Scripts/python -m scripts.generate_sample_replays   (or python scripts/...)

Writes ui/web/src/replay/sampleReplays.js: five deterministic journeys from
the real simulation harness, one per core surface of the site —

    score          a first-time investor reads a stock card
    portfolio      a concentrated employer-stock book goes through attribution
    community      a hyped, misleading post meets a HIGH model score
    crash          a panicky user under the crisis-safe presentation
    comprehension  a low-literacy user answers the question battery

Seeds are fixed and were CHOSEN so each surface's signature events actually
appear in its journey (a community sample without a report event demonstrates
nothing). That is curation of which deterministic run to bundle — the runs
themselves are untouched harness output, reproducible byte-for-byte from the
seeds below, and the viewer's permanent banner already states that every
journey is developer-encoded assumption, not a real person.
"""

from __future__ import annotations

import json
from pathlib import Path

from stock_risk.simulation import scenarios as scn
from stock_risk.simulation.events import config_hash
from stock_risk.simulation.profiles import Archetype, generate_cohort
from stock_risk.simulation.replay import build_replay
from stock_risk.simulation.tasks import (
    run_comprehension_check,
    run_portfolio_concentration,
    run_single_stock_analysis,
)

OUT = Path(__file__).resolve().parents[1] / "ui" / "web" / "src" / "replay" / "sampleReplays.js"

CFG = config_hash({"bundled_samples": 1})
BOOK = [
    ("EMP", 0.70, 0.55, 1.6, "Tech"),
    ("A", 0.10, 0.25, 0.9, "Health"),
    ("B", 0.10, 0.22, 0.8, "Utilities"),
    ("C", 0.10, 0.20, 0.7, "Staples"),
]


def _samples() -> list[dict]:
    novice = generate_cohort(Archetype.FIRST_TIME_RETAIL, 1, seed=2026)[0]
    employer = generate_cohort(Archetype.CONCENTRATED_EMPLOYER_STOCK, 1, seed=4)[0]
    social = generate_cohort(Archetype.COMMUNITY_INFLUENCED, 1, seed=2)[0]
    panicky = generate_cohort(Archetype.MARKET_CRASH_USER, 1, seed=3)[0]
    low_lit = generate_cohort(Archetype.LOW_FINANCIAL_LITERACY, 1, seed=1)[0]

    comp_log, _ = run_comprehension_check(low_lit, seed=7, config_hash=CFG)

    return [
        {"id": "score", "replay": build_replay(
            run_single_stock_analysis(novice, seed=7, config_hash=CFG))},
        {"id": "portfolio", "replay": build_replay(
            run_portfolio_concentration(
                employer, seed=11, config_hash=CFG,
                positions_spec=BOOK, show_attribution=True))},
        {"id": "community", "replay": build_replay(
            scn.run_community_misinformation(social, seed=0, config_hash=CFG))},
        {"id": "crash", "replay": build_replay(
            scn.run_market_crash(panicky, seed=6, config_hash=CFG, crisis_safe=True))},
        {"id": "comprehension", "replay": build_replay(comp_log)},
    ]


def main() -> None:
    samples = _samples()
    # Determinism check: a second pass must be identical, or the bundle would
    # drift between regenerations.
    assert json.dumps(samples, sort_keys=True) == json.dumps(_samples(), sort_keys=True)

    body = json.dumps(samples, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// GENERATED by scripts/generate_sample_replays.py — do not hand-edit.\n"
        "// Five deterministic journeys from the simulation harness, one per core\n"
        "// surface. Regenerate with: python -m scripts.generate_sample_replays\n"
        f"export const SAMPLE_REPLAYS = {body}\n",
        encoding="utf-8",
    )
    for s in samples:
        print(f"  {s['id']}: {len(s['replay']['steps'])} steps")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
